# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 268)
        MainWindow.setMinimumSize(QtCore.QSize(500, 0))
        MainWindow.setMaximumSize(QtCore.QSize(750, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_pdf = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pdf.setMinimumSize(QtCore.QSize(150, 35))
        self.btn_pdf.setStyleSheet("QPushButton#btn_pdf {\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(180, 180, 180);\n"
"    border-radius:15px;\n"
"    font: bold 12px;\n"
"}\n"
"QPushButton#btn_pdf:hover {\n"
"    background-color:rgb(85, 170, 127);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QPushButton#btn_pdf:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"    color: rgb(25, 25, 25);\n"
"\n"
"}")
        self.btn_pdf.setObjectName("btn_pdf")
        self.gridLayout.addWidget(self.btn_pdf, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(200, 40, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setObjectName("label_status")
        self.gridLayout.addWidget(self.label_status, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.label_remain = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_remain.setFont(font)
        self.label_remain.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_remain.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_remain.setObjectName("label_remain")
        self.gridLayout_2.addWidget(self.label_remain, 5, 2, 1, 1)
        self.label_debt = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_debt.setFont(font)
        self.label_debt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_debt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_debt.setObjectName("label_debt")
        self.gridLayout_2.addWidget(self.label_debt, 3, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 3, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 5, 3, 1, 1)
        self.label_savings = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_savings.setFont(font)
        self.label_savings.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_savings.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_savings.setObjectName("label_savings")
        self.gridLayout_2.addWidget(self.label_savings, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 6, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem5, 2, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem6, 4, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dateEdit = QtWidgets.QDateEdit(self.tab_2)
        self.dateEdit.setMinimumSize(QtCore.QSize(100, 35))
        self.dateEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(2021, 5, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_3.addWidget(self.dateEdit, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setMinimumSize(QtCore.QSize(0, 35))
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setMinimumSize(QtCore.QSize(0, 35))
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setMinimumSize(QtCore.QSize(0, 35))
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 5, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_3.addItem(spacerItem7, 4, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 3, 9, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem9, 6, 6, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem10, 0, 6, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_3.addItem(spacerItem11, 2, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 35))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 1, 4, 1, 4)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem12, 3, 0, 1, 1)
        self.btn_save = QtWidgets.QPushButton(self.tab_2)
        self.btn_save.setMinimumSize(QtCore.QSize(0, 35))
        self.btn_save.setObjectName("btn_save")
        self.gridLayout_3.addWidget(self.btn_save, 5, 6, 1, 2)
        self.lineEdit_remark = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_remark.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_remark.setObjectName("lineEdit_remark")
        self.gridLayout_3.addWidget(self.lineEdit_remark, 3, 2, 1, 6)
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setMinimumSize(QtCore.QSize(0, 35))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setMinimumSize(QtCore.QSize(0, 35))
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 5, 4, 1, 1)
        self.lineEdit_amount = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_amount.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.lineEdit_amount.setFont(font)
        self.lineEdit_amount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_amount.setObjectName("lineEdit_amount")
        self.gridLayout_3.addWidget(self.lineEdit_amount, 5, 2, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_pdf.setText(_translate("MainWindow", "Save as PDF"))
        self.label_status.setText(_translate("MainWindow", "Status:"))
        self.label_remain.setText(_translate("MainWindow", "95,000"))
        self.label_debt.setText(_translate("MainWindow", "5,000"))
        self.label_8.setText(_translate("MainWindow", "Rs."))
        self.label_5.setText(_translate("MainWindow", "Total Remaining:"))
        self.label.setText(_translate("MainWindow", "Savings"))
        self.label_3.setText(_translate("MainWindow", "Debt:"))
        self.label_10.setText(_translate("MainWindow", "Rs."))
        self.label_savings.setText(_translate("MainWindow", "100,000"))
        self.label_9.setText(_translate("MainWindow", "Rs."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Current Amount"))
        self.label_11.setText(_translate("MainWindow", "Date"))
        self.label_12.setText(_translate("MainWindow", "Remark"))
        self.label_14.setText(_translate("MainWindow", "Amount"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Income"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Expense"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Debt"))
        self.btn_save.setText(_translate("MainWindow", "Save"))
        self.label_13.setText(_translate("MainWindow", "Type"))
        self.label_15.setText(_translate("MainWindow", "Rs."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "New Entry"))

